apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  name: ocs-operator
  channel: stable-4.7
  source: redhat-operators
  sourceNamespace: openshift-marketplace
