apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaImageTag: latest
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 4Gi
  giteaAdminUser: gitadmin
  giteaAdminPassword: openshift
  giteaAdminEmail: gitadmin@example.opentlc.com
