apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus
  namespace: nexus
spec:
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  useRedHatImage: true
  serverOperations:
    disableRepositoryCreation: true
  generateRandomAdminPassword: false
  networking:
    expose: true
    tls:
      mandatory: true
  replicas: 1
  persistence:
    persistent: true
