apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: Sonatype Nexus artifact repository and container image registry
    openshift.io/display-name: Nexus
  name: nexus
spec:
  finalizers:
  - kubernetes
